### ISSUE TITLE
Installloop to 0.0.2

### ISSUE THREAD

**Issue by mindfest** [kantlivelong/OctoPrint-SmartPreheat#3] opened 2020-05-03 11:46 UTC
#### What were you doing?

1. Installed SmartPreheat through Octopi plugin manager
2. Restarted the server
3. Confirmed updatemessage to version 0.0.2
4. Restarted the server
5. Another update message appeared
6. Confirmed again to see what happens
7. Then i saw in the message box that only version .0.01 was installed again through the updater
8. After restart the update message was there again
9. Uninstalled SmartPreheat plugin

#### Version of OctoPrint-SmartPreheat
0.0.1

#### Operating System running OctoPrint
Octopi 1.4.0 on Raspberry Pi 3b

#### Printer model & used firmware incl. version
Anet A8, Merlin 2.0.5.3

**Comment by ojaksch** [comment] 2020-05-03 13:23
Same here. Took a look at the package and found that setup.py identifies itself as **plugin_version = "0.0.1"**

**Comment by buzzlaker** [comment] 2020-05-03 23:17
Confirmed as well.

**Comment by nikcoultas** [comment] 2020-05-04 10:24
Yup, same here.

**Comment by matburnham** [comment] 2020-05-04 19:37
![image](https://user-images.githubusercontent.com/1058493/81006179-fb1c1d00-8e46-11ea-8f27-17d9746e3c32.png)

**Comment by ptwats** [comment] 2020-05-05 13:21
Here is a log file if that helps.
[plugin_pluginmanager_console.log.txt](https://github.com/kantlivelong/OctoPrint-SmartPreheat/files/4580948/plugin_pluginmanager_console.log.txt)

**Comment by kantlivelong** [comment] 2020-05-05 19:18
Apparently this repo got marked as unwatched for me. Doh!

I forgot to bump the version in setup.py but 0.0.3 was just released which fixes a parsing issue. Give it a go and let me know.

**Comment by matburnham** [comment] 2020-05-05 21:16
Works for me. 👍

**Comment by kantlivelong** [comment] 2020-05-05 21:18
Marking as solved then.

Apologies for the delay, had no idea I even had tickets open.

**Closed by kantlivelong** 2020-05-05 21:18 UTC
Labels: bug, solved
